name: Java Quality + Telegram

on:
  pull_request:
    branches: [ "dev" ]
    types: [ closed ]

jobs:
  quality:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/ticket-') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Checkstyle
        run: |
          mvn clean verify | tee report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quality-report
          path: report.txt

  telegram:
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ID_GROUP }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="PR merged into dev in repo $GITHUB_REPOSITORY. Check Actions for report."
