name: Java Pipeline

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]

permissions: 
  contents: read
  pull-requests: write
  actions: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Build and run tests
        run: mvn clean verify -Dcheckstyle.skip=true
       
      - name: Generate report
        if: always()
        run: |
          mkdir peresdReport
          echo "Pipeline Report" > peresdReport/peresdReport.txt
          echo "Repository: $git_rep" >> peresdReport/peresdReport.txt
          echo "Branch: $git_ref_n" >> peresdReport/peresdReport.txt
          echo "Commit: $git_sha" >> peresdReport/peresdReport.txt
          echo "Status: ${{ job.status }}" >> peresdReport/peresdReport.txt
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: peresdPip-report
          path: peresdReport/peresdReport.txt

      - name: Message Telegram
        if: always()
        continue-on-error: true
        run: |
          Date = $(date '+%Y-%m-%d')
          URL = "https://github.com/${git_rep}/actions/runs/${git_run}"

          txt = "Pipeline end

            репозиторий: $git_rep
            ветка: $git_ref_n
            дата: $Date
            статус работы: ${{ job.status }}

            Запуск:
            $URL"
              curl -s -X post "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
              -d id_cht = "${{ secrets.ID_GROUP}}" \
              --data-urlencode text = "$txt"
            

   
    

